### ISSUE TITLE
Classical Evaluation code cannot run

### ISSUE THREAD

**Issue by PosoSAgapo** [taoyds/test-suite-sql-eval#9]
I have tried on my macos laptop and a centos server with your classical evaluation code. It returns TypeError: cannot unpack non-iterable coroutine object in the classical_evaluation.py code. The problem seems to be caused by the multiprocess module in the code.

**Comment by chiragdaryani** [comment]
Same issue @PosoSAgapo  @taoyds  @ruiqi-zhong Does anybody know the fix?

**Comment by AdeelGH** [comment]
I'm having the same issue.

**Comment by sherlock30** [comment]
Any resolutions yet?

**Comment by wangzaistone** [comment]
have the same issue too ,evaluate_classical_test2.py:64: RuntimeWarning: coroutine 'exec_on_db' was never awaited
  flg, gold_result = exec_on_db(testcase_path, gold_query, timeout=GOLD_TIMEOUT)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
  0%|                                                                                                                                                                                                                                   | 0/196 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/anaconda/envs/RESDSQL/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "evaluate_classical_test2.py", line 64, in judge
    flg, gold_result = exec_on_db(testcase_path, gold_query, timeout=GOLD_TIMEOUT)
TypeError: cannot unpack non-iterable coroutine object

**Comment by BahozHagi** [comment]
I Just mad a quick fix:

https://github.com/taoyds/test-suite-sql-eval/pull/22
